spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ENV_DB_HOST:localhost}:${ENV_DB_PORT:3306}/${ENV_DB_NAME:todo}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${ENV_DB_USER:root}
    password: ${ENV_DB_PASSWORD:mysql}
    initialization-mode: always
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
